### ISSUE TITLE
Resources should be installed when it's uploaded

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/hardware-observer-operator#114]
Currently, resources will only be installed when the charm is first installed. It would be better that the resources can be installed whenever they are uploaded (of course, we should install the resources if they are needed). This could be useful if the operator decided to change the resources, or if there are new hardware added to the servers, and the operator want to also observe that hardware.

**Comment by Pjack** [comment]
This issue is used to track the potential problem found in #110 . 
If the corresponding resource is not installed during charm deployment (because of network or hardware issue), after the hardware available, there should be a mechanism to trigger the installation of resource and enable the collector.

**Comment by jneo8** [comment]
We decide to use action to recover that.
