### ISSUE TITLE
Redfish sensors based alerts has no duration so could flapping when the value is fluctuating around max value.

### ISSUE THREAD

**Issue by err404r** [canonical/hardware-observer-operator#146]
I faced a two issues today first is the behavior similar to [Issue#112](https://github.com/canonical/hardware-observer-operator/issues/112) This time Fan readings are flapping from None to value and back, on the same server.

And this generates a huge amount of alerts. I will add a small duration to alert rule form 1 to 3 minutes probably.
To avoid false positives caused by flapping redfish api or something like that.

**Comment by jneo8** [comment]
close & re-open to trigger the github to JIRA action.

**Comment by err404r** [comment]
The same applies to RedfishStorageControllerHealthNotOk alerts and probably other alerts, we need take into account that readings from redfish are not perfectly stable

**Comment by dashmage** [comment]
The Redfish "HealthNotAvailable" alerts have been [removed](https://github.com/canonical/hardware-observer-operator/commit/61173dd65f9032788b7b739e8bec17cf92196347) since in a lot of cases the data might not be available but we wouldn't want an alert for each of them. The original linked issue has also been resolved.

@err404r - would this solve your issues as well?

**Comment by dashmage** [comment]
Thanks for your comment and I understand your intention better. Let me check in with the rest of the team for their opinion and then pick a suitable duration time.
