### ISSUE TITLE
SmartAttributeWarning seems to configured incorrectly

### ISSUE THREAD

**Issue by err404r** [canonical/hardware-observer-operator#358]
rev 84
In the freshly deployed cloud I'm observing warning for each drive. So most likely something is not right with the definition could you please check alert definition

**Comment by aieri** [comment]
@err404r could you please provide some more detail? Which attributes are triggering the warning? And can you confirm that the reading is incorrect (i.e. the exporter reports a metrics value that is different from what you get via `smartctl`)?

**Comment by przemeklal** [comment]
There are 324 alerts firing on this env. I'm attaching a screenshot showing a couple of examples. The alert description is not too helpful either. Most of these alerts seem to be triggered for `attribute_flags_long=event_count` and the value is `100` . They seem to be firing for every monitored machine on this env.

![image](https://github.com/user-attachments/assets/7ae01906-fcce-4f29-83b9-06a8589582f0)

**Comment by Deezzir** [comment]
@err404r @przemeklal, Can you confirm that the `smartctl` CLI reports the same raw values? It makes sense to fire those alerts because those attributes correspond to the following SMART errors:

- 5: `Reallocated_Sector_Ct`
- 187: `Reported_Uncorrect`
- 197: `Current_Pending_Sector`
- 198: `Offline_Uncorrectable`
- 188: `Command Timeout`

See: https://www.backblaze.com/blog/what-smart-stats-indicate-hard-drive-failures/
