### ISSUE TITLE
Replace discover with redfish basic login.

### ISSUE THREAD

**Issue by jneo8** [canonical/hardware-observer-operator#61]
```python
import redfish
from redfish.discovery import discovery
from redfish.rest.v1 import (
    RetriesExhaustedError,
    SessionCreationError,
    InvalidCredentialsError,
)


if __name__ == "__main__":
    obj = None
    try:
        obj = redfish.redfish_client(base_url="{endpoint from ipmitool}", username="{username}", password="{password}", timeout=1, max_retry=3)
        obj.login(auth="basic")
    except (SessionCreationError, InvalidCredentialsError) as e:
        # Can find endpoint but Credential is wrong
        print(e)
    except RetriesExhaustedError as e:
        # Can't find endpoint
        print(e)
    finally:
        if obj:
            # Login success
            obj.logout()

```

The current discover is not only just finding the local redfish endpoint but also using SSDP to find available redfish services in the same network. Instead of using `redfish.discover`, we can define a discover function which only try to login the local's BMC with the address found by ipmitool. we can use code above to verify if the redfish is available

**Comment by dashmage** [comment]
This would really help us simplify and avoid the issues with the `discover_ssdp()` method. Looks like we're essentially merging the functionality for `redfish_call_success` and `redfish_service_available`. 

Questions:
- Is there any specific reason we're passing `auth="basic"` rather than `auth="session"` to the `login` method?
- Do you suggest that we also change the hw-verifier detection for redfish so that if `RetriesExhausted` exception is raised while logging in, then redfish doesn't exist on the machine and we won't enable the collector? But there might be a case where redfish is present but we're not able to login due to some network issue for example and this raises the `RetriesExhausted` exception.
- If that's the case, then would `redfish_call_success` metric fail only when there is invalid credentials or the HTTP session was not created?

The only sad part is that we spent quite a bit of time optimising and refactoring the discover code (cache, staticmethod etc.)
