### ISSUE TITLE
Charm resources are 0 bytes

### ISSUE THREAD

**Issue by dparv** [canonical/hardware-observer-operator#70]
Seems all resources on charmhub are 0 bytes:

![image](https://github.com/canonical/hardware-observer-operator/assets/42830406/f5b4fcfc-6a1e-483a-b240-36f3fbdd1bd8)

**Comment by agileshaw** [comment]
Maybe @jneo8, @chanchiwai-ray, @sudeephb and @dashmage have more information, but usually 0 byte resources are intentional (e.g. [prometheus2](https://charmhub.io/prometheus2/resources/core), [charm-prometheus-juju-exporter](https://charmhub.io/prometheus-juju-exporter/resources/exporter-snap)). These are placeholders in case users need to supply local files at deployment time.

**Comment by Pjack** [comment]
We cannot republish the debian file. It's illegal. You have to download the file and upload by yourself. Similiar to charm-hw-health.

![image](https://github.com/canonical/hardware-observer-operator/assets/1013484/70613aeb-5126-462a-ad8c-39c5ebe1a64b)

We also mention it in the index page.
https://charmhub.io/hardware-observer

Therefore, this is an invalid issue. I will close the issue if no further concern

**Comment by jneo8** [comment]
Fix in #73
