### ISSUE TITLE
Allow enabling collectors from the charm

### ISSUE THREAD

**Issue by sudeephb** [canonical/hardware-observer-operator#74]
If, for whatever reason, the required collector is not activated by the charm automatically, the user has to ssh into the machine and re-run the service with a different configuration. Instead of this, it would be nice to have a way from the charm itself(eg. an action) to enable collectors according to user's choice.

**Comment by jneo8** [comment]
The issue of it is because there is not configure for single unit in juju.

So imagine you provide this config, and then

- The resource/package will be fetch/install on every units.
- The collector will be active on every units.

I am not sure it's a good practice for debugging on one unit because it will have a side effects.

https://discourse.charmhub.io/t/per-unit-configuration/2261/4

One way to do this is we still provide this kind of configure but user need to segregate different servers to different application for this approach.

(Currently install two hardware-observer charm may cause an issue because the config file is in the same path)

**Comment by jneo8** [comment]
One idea from me is maybe we can provide a juju action which helps us to debugging. The action will

- Fetch the required resource and install
- Run prometheus collector's code directly(We maybe need to provide some simple cli in exporter repo)
- Remove resource

**Comment by aieri** [comment]
I think this may be already somewhat covered by the hardware redetection action. If this is still needed please reopen.
